### ISSUE TITLE
Add a Support section with settings and other debug information

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#191] opened 2021-04-05 01:51 UTC
If a customer has a support question, then getting all the information about their setup can be tricky, involving asking the customer to send screenshots of their information.

To make communications easier, we could add a new section / tab to the settings page, which is simply a textarea of Parse.ly plugin settings, and maybe a list of other active plugins (since they may be related to an issue as well).

Add a Copy button to make it easier to copy.

**Comment by acicovic** [comment] 2022-01-27 12:12
@GaryJones mentioned the alternative idea of including a Site Health Info item with Parse.ly debug details. Noting it here for completeness and so we can decide the best approach.

**Comment by acicovic** [comment] 2022-04-20 15:58
The Site Health Info item issue is tracked in #638.

**Comment by acicovic** [comment] 2022-05-12 11:22
This is now at least partly addressed in #866.

**Comment by mehmoodak** [comment] 2022-12-22 10:48
The requirments of these ticket has been met and changes has been made on Site Health screen to show all the necessary information. The only remaining ask is to make the copy easier which I think we can let go as Site Health already have all the information and customers can send full screenshot of that screen which can then help us to find the root cause.

**Closed by mehmoodak** 2022-12-22 10:48 UTC
Labels: Type: Enhancement
