### ISSUE TITLE
Only make `/profile` calls when a widget is in use

### ISSUE THREAD

**Issue by joshuarrrr** [Parsely/wp-parsely#130] opened 2019-04-30 21:58 UTC
to avoid unnecessary network load and storage

**Comment by GaryJones** [comment] 2021-03-27 18:02
[Docs about `/profile` endpoint](https://www.parse.ly/help/api/recommendations#get-profile).

**Comment by GaryJones** [comment] 2021-04-11 22:59
The only instance of a call to `/profile` endpoint is [here](https://github.com/Parsely/wp-parsely/blob/cfeb6a9444933d71f002437de2d2856a0cf3cf01/parsely-javascript.php#L25) in the main JavaScript file.

Noting that this will change location (into a .js file) in an upcoming PR cc @jblz.

**Comment by jblz** [comment] 2021-05-04 14:15
As of #236, the [script](https://github.com/Parsely/wp-parsely/blob/3cca62a4c228af6bd8893e744e710fb6b4269e94/src/js/lib/init-api/index.js) that pings the `/profile` endpoint is only sourced when the `api_secret` option value is set:

https://github.com/Parsely/wp-parsely/blob/3cca62a4c228af6bd8893e744e710fb6b4269e94/src/class-parsely.php#L1142-L1151

@hbbtstar  Should we change the behavior further by only sourcing the script when `is_active_widget` hits?

**Comment by jblz** [comment] 2021-05-05 15:08
Closing this as intended behavior (now that the script is only loaded when the API is in use)

**Closed by jblz** 2021-05-05 15:08 UTC
Labels: Type: Bug
