### ISSUE TITLE
Auto recrawl posts changed in WP plugin

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1073] opened 2022-09-08 16:09 UTC
## Is your feature request related to a problem?
Yes; customers often update their content and metadata when it is outdated, benefits from an SEO refresh, etcetera.

We have documentation https://www.parse.ly/help/kb/whats-a-recrawl around adding webhooks to a CMS to automatically ping the /recrawl endpoint every time an article is updated. We could add that functionality to the plugin to keep up with changes for customers. Not sure how this would affect API performance as this could be a huge number of calls potentially, but it seems like a good idea to investigate.

## Describe the solution you'd like
Use recrawl webhook to automatically recrawl posts that are changed in WP Plugin

## Describe alternatives you've considered
None

## Additional context
Original request made by Evan Twidwell, adding him to the issue.

**Comment by chriszarate** [comment] 2022-09-08 18:56
> Not sure how this would affect API performance as this could be a huge number of calls potentially, but it seems like a good idea to investigate.

Is the request body parsed at all? We could set some object properties that would allow us to triage a backlogged queue:

```
POST https://dash.parsely.com/<API_KEY>/ping_crawl?secret=<API_SECRET>&url=<URL>

{
  "event_source": "wp-parsely",
  "event_type": "save_post"
}
```

**Comment by GaryJones** [comment] 2022-09-09 10:09
I know some media customers will make 2-3 saves to a breaking news article in a minute, so the pinging for a recrawl probably needs to be queued async and done every 5 minutes or something.

**Comment by chriszarate** [comment] 2022-09-09 14:33
Loose requirements:

- Determine if pertinent metadata has actually changed before queuing a recrawl.
- Send recrawl requests async so that we aren't blocking the critical `save_post` path.
- Debounce repeated recrawl requests to make sure that we don't abuse the API
- Talk to Parse.ly engineers about this new feature to make sure that the API is prepared for an increase in requests

**Comment by mehmoodak** [comment] 2022-12-30 09:48
Duplicate of #265 (mentioned this ticket as a comment so that info on this ticket can be fruitful there)

**Closed as completed by mehmoodak** 2022-12-30 09:48 UTC
Labels: Enhancement, wp-parsely
