### ISSUE TITLE
Logo setting - allow to choose from Media library

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#227] opened 2021-04-15 23:20 UTC
<img width="656" alt="Screenshot 2021-04-16 at 00 19 25" src="https://user-images.githubusercontent.com/88371/114949695-6ccb5c00-9e49-11eb-886f-f90ee8d9c2fc.png">

The Logo setting is currently a text input field (and a narrow one at that) - we can make it more useful by letting users select an image directly from the media library.

**Comment by acicovic** [comment] 2022-01-04 10:24
Some feedback would be useful here.

1. Would we want for any reason to keep the text input?
2. Would we want a selected image preview?

**Comment by GaryJones** [comment] 2022-01-05 00:55
1. The value saved via the current text field should still be the value saved if it had been re-populated via the media library picker. This would support someone potentially using a value that was not from the current site (maybe a logo from blog 1 subsite on a multisite install).

2. Yes - like the Featured Image feature when editing a post, if the image is from the current site media library (may be undesirable to render an image from a different site). The preview should be in addition to, and not replace, the URL string in a form field.

**Comment by acicovic** [comment] 2022-01-06 10:57
Currently #570 offers an implementation with a "Browse" button, but no preview yet as I've got second thoughts about it.

The preview should be bound to the value of the text input and refresh whenever there is a change there. If the value is a valid image URL, then show it. However, if we don't want to show a preview for external URLs (which can be a valid point IMO), it could get confusing as the preview won't show anything even for valid (external) URLs, potentially causing confusion.

If having a preview is a must have, we can certainly work out a solution. Personally I'm not sure since this will usually be a "set and forget" type of thing.

And of course, all this brings up the question of whether we should actually allow users to specify an external URL for this.

**Comment by acicovic** [comment] 2022-01-12 15:18
In the team meeting we've had today, we decided to go forward just with the browse button for the time being.

We can always reiterate later on this if needed.

**Comment by acicovic** [comment] 2022-01-21 17:14
Marking this as closed, since #570 should get merged soon.

**Comment by pauarge** [comment] 2022-01-21 18:44
We shouldn’t close the issues until the PR is closed. Actually, when the PR gets merged, the issue is automatically closed.

**Closed as completed** 2022-01-25 10:04 UTC
Labels: Enhancement, wp-parsely
