### ISSUE TITLE
Support REST API output

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#189] opened 2021-04-05 01:45 UTC
A decoupled app powered by WordPress may want to get Parse.ly constructed metadata for a post/page/archive/home/etc. via the REST API, so that it can be inserted into the decoupled application.

We should find a way to provide that, by adding fields to built-in REST API endpoints, or offering a new route and endpoint.

**Comment by pauarge** [comment] 2021-11-16 11:38
Duplicate of https://github.com/Parsely/wp-parsely/issues/487

**Closed by pauarge** 2021-11-16 11:38 UTC
Labels: Type: Enhancement
