### ISSUE TITLE
ping recrawl endpoint on publish_post action

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#92] opened 2018-04-10 17:50 UTC
see here for details on the `publish_post` action hook: 

https://codex.wordpress.org/Plugin_API/Action_Reference/publish_post

**Comment by mehmoodak** [comment] 2022-12-22 10:45
Duplicate of #265. Keeping that because there is more information in that ticket.

**Closed by mehmoodak** 2022-12-22 10:45 UTC
Labels: Type: Enhancement
